### ISSUE TITLE
Ask for an example

### ISSUE THREAD

**Issue by Lillian-Wangs** [vincenzoml/topochecker#3]
"eval.csv" is a csv file, with three or more columns. Each row takes the form
state point prop1 prop2 ... propN
each of prop1 ... propN may be in the form string=int, associating a quantity to a proposition. Actually, the first form is a shorthand for string=1, and omitting a string makes its value equal to 0.

Where should code 'string=2' be placed in the program?Could you give me an example if you are convenient?Thank you!

**Comment by vincenzoml** [comment]
Here I am, but please consider voxlogica if you are analysing space.
There's a new experimental branch for graphs which is still very
experimental but will be the future topochecker; the imaging branch is
stable; topochecker will no longer be maintained.

https://vincenzoml.github.io/VoxLogicA/

Said this, an example of what you're looking for can be found in the
repository, in the folder "examples/test-square_grid_quantitative":

once you generate the model using "ocaml generate_model.ml", you will see
the file "eval.csv", containing lines of the form

0,0,a=0
0,1,a=1
0,2,a=2
0,3,a=3
0,4,a=4
...

and so on. This means that attribute "a" in state 0, point 1 has value "1"
(for instance).

Hope this helps, let me know if you have any questions

Vincenzo

Il giorno gio 16 apr 2020 alle ore 19:52 桃之夭夭 <notifications@github.com> ha
scritto:

**Comment by Lillian-Wangs** [comment]
@vincenzoml 
Thank you very much.Your answer is very useful, I neglected the folder.
And thanks for your advice about VosLogicA,I will try to use it.
